# This is a basic workflow that is manually triggered

name: 01a Hola Mundo
on:
  workflow_dispatch:
jobs:
  hola-mundo:
    runs-on: ubuntu-latest
    steps:
    - name: Hola Mundo
      run: echo "¡Hola Mundo!"
