name: 02 - Evento issue
on:
  push:
    paths:
      - '**/*'
      - '!README.md'    # Exceptuamos los cambios en README.md
  issues:
    types: [opened]  # Solo cuando se cree una nueva issue
jobs:
  hola-mundo:
    runs-on: ubuntu-latest
    steps:
      - name: Hola mundo
        run: echo "¡Hola Mundo!"
